module.exports = {
  important: true,
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        transparent: "transparent",
        current: "currentColor",
        white: "#ffffff",
        purple: "#3f3cbb",
        midnight: "#012169",
        metal: "#565584",
        tahiti: "#3ab7bf",
        silver: "#ecebff",
        "bubble-gum": "#ff77e9",
        bermuda: "#78dcca",
        gray: "#ADADAD",
        black: "#232A38",
        blue: "#0659ED",
        tableborder: "#0659ED",
        lightgreen: "#129920",
        navyblue: "#063970",
        darkgray: "#555555",
        yellow: "#dea109",
        red: "#Ea2a0b",
        saffron: "#Eac00b",
        highlight: "#f0f3f8",
      },
    },
  },
  plugins: [],
};
